MVC_Project/work_01/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using work_01.Models;
using work_01.ViewModels;
using System.IO;

namespace work_01.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item

        RestuarentDbContext db = new RestuarentDbContext();
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.categories = new SelectList(db.ItemCategories, "ItemCategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(ItemViewModel tvm)
        {
            if (ModelState.IsValid)
            {
                if (tvm.Picture != null)
                {
                    string filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(tvm.Picture.FileName));
                    tvm.Picture.SaveAs(Server.MapPath(filePath));

                    Item item = new Item
                    {
                       ItemName = tvm.ItemName,
                       ItemPrice = tvm.ItemPrice,
                       Quantity = tvm.Quantity,
                       PurchaseDate = tvm.PurchaseDate,
                       IsAvailable = tvm.IsAvailable,
                       Category = tvm.Category,
                       ItemPicture = filePath
                      
                    };
                    db.Items.Add(item);
                    db.SaveChanges();
                    return PartialView("_success");
                }
            }
            ViewBag.categories = new SelectList(db.ItemCategories, "ItemCategoryId", "CategoryName");
            return PartialView("_error");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();

            }
            ItemViewModel tvm = new ItemViewModel
            {
                ItemId = item.ItemId,
                ItemName=item.ItemName,
                ItemPrice = item.ItemPrice,
                Category = (int)item.Category,
                Quantity = item.Quantity,
                PurchaseDate = item.PurchaseDate,
                IsAvailable = item.IsAvailable,
                PicturePath = item.ItemPicture
            };
            ViewBag.categories = new SelectList(db.ItemCategories, "ItemCategoryId", "CategoryName");

            return View(tvm);
        }

        [HttpPost]
        public ActionResult Edit(ItemViewModel tvm)
        {
            if (ModelState.IsValid)
            {
                string filePath = tvm.PicturePath;
                if (tvm.Picture != null)
                {
                    filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(tvm.Picture.FileName));
                    tvm.Picture.SaveAs(Server.MapPath(filePath));

                    Item item = new Item
                    {
                        ItemId = tvm.ItemId,
                        ItemName = tvm.ItemName,
                        ItemPrice = tvm.ItemPrice,
                        Quantity = tvm.Quantity,
                        PurchaseDate = tvm.PurchaseDate,
                        IsAvailable = tvm.IsAvailable,
                        Category = tvm.Category,
                        ItemPicture = filePath
                    };
                    db.Entry(item).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    //return RedirectToAction("Index");
                }
                else
                {
                    Item item = new Item
                    {

                        ItemName = tvm.ItemName,
                        ItemPrice = tvm.ItemPrice,
                        Quantity = tvm.Quantity,
                        PurchaseDate = tvm.PurchaseDate,
                        IsAvailable = tvm.IsAvailable,
                        Category = tvm.Category,
                        ItemPicture = filePath
                    };
                    db.Entry(item).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    //return RedirectToAction("Index");
                }
            }
            ViewBag.categories = new SelectList(db.ItemCategories, "ItemCategoryId", "CategoryName");
            return PartialView("_success");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Item item = db.Items.Find(id);
            string file_name = item.ItemPicture;
            string path = Server.MapPath(file_name);
            FileInfo file = new FileInfo(path);
            if (file.Exists)
            {
                file.Delete();
            }
            db.Items.Remove(item);
            db.SaveChanges();
            return PartialView("_deleteSuccess");
        }



    }


}

MVC_Project/work_01/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using work_01.Models;

namespace work_01.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        RestuarentDbContext db = new RestuarentDbContext();
        public ActionResult Index()
        {
            return View(db.Orders.ToList());
        }
    }
}

MVC_Project/work_01/Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using work_01.Models;

namespace work_01.Controllers
{
    public class OrderDetailController : Controller
    {
        // GET: OrderDetail
        RestuarentDbContext db = new RestuarentDbContext();
        public ActionResult Index()
        {
            return View(db.OrderDetails.ToList());
        }
    }
}

MVC_Project/work_01/Controllers/ReportsController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace work_01.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RestuarentReport()
        {
            try
            {
                string str = @"Data Source=.;Initial Catalog=MVC_Project2(second);Integrated Security=True";
                SqlConnection con = new SqlConnection(str);
                SqlDataAdapter ada = new SqlDataAdapter();
                SqlCommand command = con.CreateCommand();
                command.CommandText = "select * from Items i join ItemCategories c on i.Category = c.ItemCategoryId";
                SqlDataAdapter da = new SqlDataAdapter(command);
                DataSet ds = new DataSet();
                da.Fill(ds, "Items");
                ReportDocument rd = new ReportDocument();
                string rptPath = System.Web.HttpContext.Current.Server.MapPath("~/Report/RestuarentReport.rpt");
                rd.Load(rptPath);
                rd.SetDataSource(ds);
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Flush();
                rd.Close();
                rd.Dispose();
                return File(stream, System.Net.Mime.MediaTypeNames.Application.Pdf);

               

            }
            catch (Exception ex)
            {
                return Content("<h2>Error:" + ex.Message + "</h2>", "text/html");
            }
        }
    }
}

MVC_Project/work_01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Md. Arman Hossain" />
    <meta charset="utf-8" lang="en-us" />
    <meta name="description" content="Stock Mangement project with Asp.net MVC" />
    <title>@ViewBag.Title</title>
    @RenderSection("Style", required: false)

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />

    <style type="text/css">
        body {
            margin-top: 70px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom fixed-top ">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">LOGO</a>
        <button class="navbar-toggler" type="button" data-bs-target="#menuBar" data-bs-toggle="collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @*<button class="navbar-toggler" type="button" data-bs-target="collapse" data-bs-toggle="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>*@
    <div class="navbar-collapse collapse" id="menuBar">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Item List", "Index", "Item", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Order List", "Index", "Order", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Order Details", "Index", "OrderDetail", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Transaction", "Index", "Transaction", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Category", "Index", "Category", new { }, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Report", "RestuarentReport", "Reports", new { }, new { @class = "nav-link" })
            </li>
        </ul>
        <ul class="nav navbar-nav ms-auto">
            @if (Request.IsAuthenticated)
            {
                <li>
                    @Html.ActionLink("Hello, " + User.Identity.Name + " !", "Index", "", new { @class = "nav-link" })
                </li>
                <li>
                    @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                </li>
            }
            else
            {
                <li class="active">
                    @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                </li>
                <li class="active">
                    @Html.ActionLink("Login", "LOgin", "Account", new { }, new { @class = "nav-link" })
                </li>
            }
        </ul>
    </div>
    </div>
</nav>

    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer class="container-fluid">
        <p class="text-center">&copy;@DateTime.Now.Year-MVC-Project</p>
    </footer>

    @RenderSection("Scripts", required: false)
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</body>
</html>

MVC_Project/work_01/Views/Shared/_deleteSuccess.cshtml
<div class="text-success fw-bold mb-2">
    Item Deleted Successfully!!!
</div>

MVC_Project/work_01/Views/Shared/_success.cshtml
<div class="text-success fw-bold mb-2">
    Operation Completed successfully!!!
</div>